### ISSUE TITLE
Find First and Last occurance of element in sorted array

### ISSUE THREAD

**Issue by priyanshuhaldar007** [Saikat2407/DSA_Hacktoberfest#47] opened 2022-10-11 20:37 UTC
[Leetcode question No 34](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/)

Please assign this to me

**Comment by Saikat2407** [comment] 2022-10-12 13:57
@priyanshuhaldar007 kindly Add up your solution with question link on top of the file and push it under leetcode folder

**Comment by Abulaman23** [comment] 2022-10-16 15:47
Please assign this to me!

**Comment by Saikat2407** [comment] 2022-10-16 17:00
> Please assign this to me!

assigned

**Comment by pritam1309** [comment] 2022-10-21 10:06
plz assign it to me

**Comment by Saikat2407** [comment] 2022-10-23 03:53
> plz assign it to me

sure

**Comment by nithish12345678** [comment] 2022-10-25 04:18
Hi 
@priyanshuhaldar007 , I am interested to look into this issue. if the issue is not yet resolved , Would you please assign this to me ?

**Comment by Saikat2407** [comment] 2022-10-26 05:28
> Hi @Saikat2407 , I am interested to look into this issue. if the issue is not yet resolved , Would you please assign this to me ?

sure man!

**Comment by DeveVivek** [comment] 2022-10-26 09:26
Please assign me this issue.

**Comment by Saikat2407** [comment] 2022-10-27 07:19
> Please assign me this issue.

Add up and make a PR.

**Closed** 2022-10-27 14:23 UTC
Labels: hacktoberfest
